POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Caio"
}

###

GET  http://localhost:3000/
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2FpbyIsImlhdCI6MTYxOTU0NTIxMX0.XTFWedSN3l7oIWdYAFBMdnVMB10dKC84sweSR4xC6oM